// Code generation: C header (pack/unpack), Python decoder, transmit snippets.

import { resolveRange, rangeChunks } from './bits.js';
import { ml, ident, fmtNum, hexByte, bytesToHex, hex } from './util.js';
import { exportDbc } from './dbc.js';

function cType(width, signed) {
  const w = width <= 8 ? 8 : width <= 16 ? 16 : width <= 32 ? 32 : 64;
  return `${signed ? 'int' : 'uint'}${w}_t`;
}
function cUType(width) { return cType(width, false); }
function cMask(n) { return '0x' + ((2 ** n) - 1).toString(16).toUpperCase() + 'u'; }

/** Byte chunks of a big endian range: [{byte (0 based), hi, lo, n, rshift}] (rshift = raw bits after this chunk) */
export function chunks(start, end, littleEndian = false) {
  return rangeChunks(start, end, littleEndian).map((c) => ({ byte: c.byte, hi: c.hi, lo: c.lo, n: c.n, rshift: c.shift }));
}

function commentText(s, lang) {
  return String(ml(s, lang) || '').replace(/\*\//g, '* /').replace(/\r?\n/g, ' ');
}

/** Generate a C header for one frame. */
export function genC(frame, opts = {}) { return genCMeta(frame, opts).code; }

/** Same as genC, also returns the generated fields ({fname, s: signal, width, signed, array}). */
export function genCMeta(frame, opts = {}) {
  const lang = opts.lang || 'en';
  const N = opts.prefix || ident(frame.name, `FRAME_${frame.idHex}`).toUpperCase();
  const T = `${N}_t`;
  const len = frame.length || 0;
  const L = [];
  const guard = `PSA_${ident(frame.archvar || '', 'X').toUpperCase()}_${ident(frame.netbus || '', 'X').toUpperCase()}_${N}_${frame.idHex}_H`;
  L.push(`/*`);
  L.push(` * 0x${frame.idHex} ${frame.name} - ${frame.archvar} ${frame.netbus} (${frame.type}, ${len} bytes${frame.periodMs ? `, every ${frame.periodMs} ms` : ''})`);
  if (frame.comment) L.push(` * ${commentText(frame.comment, lang)}`);
  L.push(` * Senders: ${frame.senders.join(', ') || '?'}  Receivers: ${frame.receivers.join(', ') || '?'}`);
  L.push(` * Generated by OpenLEO Explorer from DBMUXEv data (unofficial, use at your own risk).`);
  L.push(` * Bit order: PSA/Motorola, byte 1 = d[0], bit 7 = MSB (first sent).`);
  L.push(` */`);
  L.push(`#ifndef ${guard}`);
  L.push(`#define ${guard}`);
  L.push('');
  L.push('#include <stdint.h>');
  L.push('#include <string.h>');
  L.push('');
  L.push(`#define ${N}_ID 0x${frame.idHex}u`);
  L.push(`#define ${N}_LEN ${len}u`);
  if (frame.periodMs) L.push(`#define ${N}_PERIOD_MS ${frame.periodMs}u`);
  L.push('');
  const fields = [];
  const skipped = [];
  const usedNames = new Set();
  for (const s of frame.signals) {
    if (!s.pos) continue;
    if (s.unused && !opts.includeUnused) continue;
    const r = resolveRange(s.pos, len);
    const width = r.width;
    let fname = ident(s.name, 'SIG');
    if (usedNames.has(fname)) fname += `_${usedNames.size}`;
    usedNames.add(fname);
    const aligned = r.start % 8 === 0 && width % 8 === 0;
    if (len && r.end >= len * 8) { skipped.push({ s, fname, why: `outside of the ${len} bytes frame (data error)` }); continue; }
    if (s.pos.toEnd && frame.type === 'can-tp') { skipped.push({ s, fname, why: `variable length field (bytes ${s.pos.startByte}..end), read it from the reassembled payload` }); continue; }
    if (width > 64 || s.type === 'str' || s.type === 'bytes') {
      if (aligned) fields.push({ s, fname, r, width, array: width / 8 });
      else skipped.push({ s, fname, why: `${width} bit non byte-aligned field` });
      continue;
    }
    fields.push({ s, fname, r, width, signed: s.type === 'sint' });
  }
  // value tables
  for (const f of fields) {
    if (!f.s.values.length || f.s.values.length > 256) continue;
    const used = new Set();
    const defs = [];
    for (const v of f.s.values) {
      let vn = ident(ml(v.text, 'en') || (v.unused ? 'UNUSED' : `V${v.raw}`), `V${v.raw}`).toUpperCase().slice(0, 40);
      if (used.has(vn)) vn = `${vn}_${hex(v.raw)}`;
      used.add(vn);
      defs.push(`#define ${N}_${f.fname}_${vn} 0x${hex(v.raw)}u`);
    }
    L.push(`/* ${f.fname} values */`);
    L.push(...defs);
    L.push('');
  }
  L.push('typedef struct {');
  for (const f of fields) {
    const c = [f.s.bits, f.s.littleEndian ? 'little endian' : '', f.s.unused ? 'unused' : '', f.s.hasFactor || f.s.offset ? `phys = raw * ${fmtNum(f.s.factor, 10)} + ${fmtNum(f.s.offset, 10)}` : '', f.s.units, f.s.mux ? `only when ${f.s.mux.selector} in {${f.s.mux.values.join(',')}}` : '', commentText(f.s.comment, lang)].filter(Boolean).join(', ');
    if (f.array) L.push(`    uint8_t ${f.fname}[${f.array}]; /* ${c} */`);
    else L.push(`    ${cType(f.width, f.signed)} ${f.fname}; /* ${c} */`);
  }
  if (!fields.length) L.push('    uint8_t _empty; /* no documented signal */');
  L.push(`} ${T};`);
  L.push('');
  // unpack
  L.push(`/* Decode a received payload (d must hold ${N}_LEN bytes) */`);
  L.push(`static inline void ${N}_unpack(${T} *m, const uint8_t *d)`);
  L.push('{');
  if (!fields.length) L.push('    (void)m; (void)d;');
  for (const f of fields) {
    if (f.array) { L.push(`    memcpy(m->${f.fname}, &d[${f.r.start >> 3}], ${f.array});`); continue; }
    const UT = cUType(f.width);
    const parts = chunks(f.r.start, f.r.end, f.s.littleEndian).map((c) => {
      let e = `d[${c.byte}]`;
      if (c.lo) e = `(${e} >> ${c.lo})`;
      if (c.n < 8) e = `(${e} & ${cMask(c.n)})`;
      e = `(${UT})${e}`;
      if (c.rshift) e = `(${e} << ${c.rshift})`;
      return e;
    });
    if (f.signed && f.width < 64 && f.width !== 8 && f.width !== 16 && f.width !== 32) {
      L.push(`    { ${UT} r = ${parts.join(' | ')};`);
      L.push(`      if (r & ((${UT})1u << ${f.width - 1})) r |= (${UT})~((${UT})${cMask(f.width)}${f.width > 32 ? 'LL' : ''});`);
      L.push(`      m->${f.fname} = (${cType(f.width, true)})r; }`);
    } else {
      L.push(`    m->${f.fname} = (${cType(f.width, f.signed)})(${parts.join(' | ')});`);
    }
  }
  L.push('}');
  L.push('');
  L.push(`/* Encode a payload (d must hold ${N}_LEN bytes, it is cleared first) */`);
  L.push(`static inline void ${N}_pack(const ${T} *m, uint8_t *d)`);
  L.push('{');
  L.push(`    memset(d, 0, ${N}_LEN);`);
  if (!fields.length) L.push('    (void)m;');
  for (const f of fields) {
    if (f.array) { L.push(`    memcpy(&d[${f.r.start >> 3}], m->${f.fname}, ${f.array});`); continue; }
    const UT = cUType(f.width);
    L.push(`    { ${UT} r = (${UT})m->${f.fname};`);
    for (const c of chunks(f.r.start, f.r.end, f.s.littleEndian)) {
      let e = 'r';
      if (c.rshift) e = `(r >> ${c.rshift})`;
      e = `(${e} & ${cMask(c.n)})`;
      if (c.lo) e = `(${e} << ${c.lo})`;
      L.push(`      d[${c.byte}] |= (uint8_t)${e};`);
    }
    L.push('    }');
  }
  L.push('}');
  L.push('');
  const phys = fields.filter((f) => !f.array && (f.s.hasFactor || f.s.offset));
  if (phys.length) {
    L.push('/* Physical value helpers */');
    for (const f of phys) {
      L.push(`static inline double ${N}_${f.fname}_phys(${cType(f.width, f.signed)} raw) { return (double)raw * ${fmtNum(f.s.factor, 12)} + ${fmtNum(f.s.offset, 12)}; }${f.s.units ? ` /* ${String(f.s.units).replace(/\*\//g, '')} */` : ''}`);
      L.push(`static inline ${cType(f.width, f.signed)} ${N}_${f.fname}_raw(double phys) { return (${cType(f.width, f.signed)})((phys - ${fmtNum(f.s.offset, 12)}) / ${fmtNum(f.s.factor, 12)} + ${f.signed ? '(phys >= 0 ? 0.5 : -0.5)' : '0.5'}); }`);
    }
    L.push('');
  }
  if (skipped.length) {
    L.push('/* Not generated:');
    for (const s of skipped) L.push(` *   ${s.fname} (${s.s.bits}): ${s.why}`);
    L.push(' */');
    L.push('');
  }
  L.push(`#endif /* ${guard} */`);
  return { code: L.join('\n'), fields, skipped, prefix: N };
}

function pyStr(s) { return JSON.stringify(String(s ?? '')); }

/** Python decoder (no dependency) + cantools usage through the DBC snippet. */
export function genPython(frame, opts = {}) {
  const lang = opts.lang || 'en';
  const N = ident(frame.name, `FRAME_${frame.idHex}`).toUpperCase();
  const len = frame.length || 0;
  const L = [];
  L.push(`# 0x${frame.idHex} ${frame.name} - ${frame.archvar} ${frame.netbus} (generated by OpenLEO Explorer, unofficial)`);
  L.push(`# start = bit index from the first transmitted bit (byte 1 bit 7 = 0)`);
  L.push(`# chunks = [(byte index, lowest bit in the byte, bit count, shift in the raw value)], handles big and little endian`);
  L.push(`${N} = {`);
  L.push(`    'id': 0x${frame.idHex}, 'name': ${pyStr(frame.name)}, 'length': ${len},${frame.periodMs ? ` 'period_ms': ${frame.periodMs},` : ''}`);
  L.push(`    'signals': {`);
  for (const s of frame.signals) {
    if (!s.pos || (s.unused && !opts.includeUnused)) continue;
    const r = resolveRange(s.pos, len);
    if (len && r.end >= len * 8) continue;
    const vals = s.values.length && s.values.length <= 256 ? `{${s.values.map((v) => `${v.raw}: ${pyStr(ml(v.text, lang) || (v.unused ? 'unused' : ''))}`).join(', ')}}` : '{}';
    const ch = rangeChunks(r.start, r.end, s.littleEndian).map((c) => `(${c.byte}, ${c.lo}, ${c.n}, ${c.shift})`).join(', ');
    L.push(`        ${pyStr(s.name)}: dict(start=${r.start}, length=${r.width}, chunks=[${ch}], signed=${s.type === 'sint' ? 'True' : 'False'}, factor=${fmtNum(s.factor, 12)}, offset=${fmtNum(s.offset, 12)}, unit=${pyStr(s.units)}, kind=${pyStr(s.type)}${s.littleEndian ? ', little_endian=True' : ''}, values=${vals}),`);
  }
  L.push('    },');
  L.push('}');
  L.push('');
  L.push(`def decode(data: bytes, msg=${N}):`);
  L.push(`    """Decode a payload, returns {signal: (raw, physical, label)}"""`);
  L.push(`    data = bytes(data).ljust(msg['length'], b'\\x00')`);
  L.push(`    out = {}`);
  L.push(`    for name, s in msg['signals'].items():`);
  L.push(`        raw = 0`);
  L.push(`        for byte, lo, n, shift in s['chunks']:`);
  L.push(`            raw |= ((data[byte] >> lo) & ((1 << n) - 1)) << shift`);
  L.push(`        val = raw - (1 << s['length']) if s['signed'] and raw >> (s['length'] - 1) else raw`);
  L.push(`        out[name] = (raw, val * s['factor'] + s['offset'], s['values'].get(raw))`);
  L.push(`    return out`);
  L.push('');
  L.push(`def encode(values: dict, msg=${N}) -> bytes:`);
  L.push(`    """values: {signal: physical value}; missing signals are 0"""`);
  L.push(`    data = bytearray(msg['length'])`);
  L.push(`    for name, s in msg['signals'].items():`);
  L.push(`        raw = round((values.get(name, s['offset']) - s['offset']) / s['factor']) & ((1 << s['length']) - 1)`);
  L.push(`        for byte, lo, n, shift in s['chunks']:`);
  L.push(`            mask = ((1 << n) - 1) << lo`);
  L.push(`            data[byte] = (data[byte] & ~mask) | (((raw >> shift) << lo) & mask)`);
  L.push(`    return bytes(data)`);
  L.push('');
  L.push(`# With cantools (pip install cantools):`);
  L.push(`#   import cantools`);
  L.push(`#   db = cantools.database.load_string(DBC, 'dbc')   # DBC = the "DBC" snippet of this frame`);
  L.push(`#   db.decode_message(0x${frame.idHex}, bytes.fromhex('${bytesToHex(new Uint8Array(len), '')}'))`);
  return L.join('\n');
}

export function genDbcSnippet(frame, opts = {}) {
  return exportDbc([frame], { ...opts, busLabel: `${frame.archvar} ${frame.netbus}` }).text;
}

// ---------------------------------------------------------------------------
// LIN helpers
// ---------------------------------------------------------------------------

export function linPid(id) {
  const b = (n) => (id >> n) & 1;
  const p0 = b(0) ^ b(1) ^ b(2) ^ b(4);
  const p1 = 1 - (b(1) ^ b(3) ^ b(4) ^ b(5));
  return (id & 0x3F) | (p0 << 6) | (p1 << 7);
}

export function linChecksum(data, pid = null) {
  let sum = pid === null ? 0 : pid;
  for (const x of data) { sum += x; if (sum > 0xFF) sum -= 0xFF; }
  return (~sum) & 0xFF;
}

// ---------------------------------------------------------------------------
// Transmit snippets
// ---------------------------------------------------------------------------

export function txSnippets(frame, bytes, opts = {}) {
  const iface = opts.iface || 'can0';
  const hexs = bytesToHex(bytes, '');
  const arr = Array.from(bytes, (b) => '0x' + hexByte(b));
  const idw = frame.extended ? 8 : 3;
  const id = hex(frame.id, idw);
  const out = [];
  const period = frame.periodMs;
  if (frame.type === 'can' || frame.type === 'can-tp') {
    if (frame.type === 'can-tp' && bytes.length > 7) {
      out.push({ title: 'Note', lang: 'text', code: `This is an ISO-TP payload (${bytes.length} bytes): it must be segmented (first frame + consecutive frames, waiting for the flow control).\nUse the Diagnostics > ISO-TP builder, or on Linux: isotpsend -s ${id} -d ${frame.isotp && frame.isotp.flow_control_id !== undefined ? hex(frame.isotp.flow_control_id, 3) : '<fc id>'} ${iface}` });
    }
    out.push({ title: 'can-utils (Linux SocketCAN)', lang: 'sh', code: `cansend ${iface} ${id}#${hexs}${period ? `\n# periodic (every ${period} ms):\ncangen ${iface} -g ${period} -I ${id} -L ${bytes.length} -D ${hexs} -n 0` : ''}` });
    out.push({ title: 'candump -L / log line', lang: 'text', code: `(0.000000) ${iface} ${id}#${hexs}` });
    out.push({ title: 'SavvyCAN / GVRET CSV line', lang: 'text', code: `Time Stamp,ID,Extended,Dir,Bus,LEN,D1,D2,D3,D4,D5,D6,D7,D8\n0,${hex(frame.id, 8)},${frame.extended ? 'true' : 'false'},Tx,0,${bytes.length},${Array.from(bytes, hexByte).join(',')}` });
    out.push({ title: 'python-can', lang: 'python', code: `import can\nbus = can.Bus(channel='${iface}', interface='socketcan')\nmsg = can.Message(arbitration_id=0x${id}, is_extended_id=${frame.extended ? 'True' : 'False'}, data=bytes.fromhex('${hexs}'))\n${period ? `task = bus.send_periodic(msg, ${period / 1000})  # every ${period} ms` : 'bus.send(msg)'}` });
    out.push({ title: 'Arduino + MCP2515 (autowp/arduino-mcp2515)', lang: 'c', code: `#include <mcp2515.h>\nMCP2515 mcp2515(10);  // CS pin\nstruct can_frame f;\n\nvoid setup() {\n  mcp2515.reset();\n  mcp2515.setBitrate(${opts.bitrate === 500 ? 'CAN_500KBPS' : opts.bitrate === 125 ? 'CAN_125KBPS' : opts.bitrate ? `CAN_${opts.bitrate}KBPS` : 'CAN_125KBPS'}, MCP_8MHZ);  // check your crystal\n  mcp2515.setNormalMode();\n}\n\nvoid loop() {\n  f.can_id  = 0x${id}${frame.extended ? ' | CAN_EFF_FLAG' : ''};\n  f.can_dlc = ${bytes.length};\n  const uint8_t data[] = {${arr.join(', ')}};\n  memcpy(f.data, data, sizeof(data));\n  mcp2515.sendMessage(&f);\n  delay(${period || 100});\n}` });
    out.push({ title: 'ESP32 TWAI (ESP-IDF / Arduino-ESP32)', lang: 'c', code: `#include "driver/twai.h"\n// setup: twai_driver_install(&g_config, &${opts.bitrate === 500 ? 'TWAI_TIMING_CONFIG_500KBITS()' : opts.bitrate === 125 || !opts.bitrate ? 'TWAI_TIMING_CONFIG_125KBITS()' : `TWAI_TIMING_CONFIG_${opts.bitrate}KBITS()`}, &f_config); twai_start();\ntwai_message_t msg = {0};\nmsg.identifier = 0x${id};\nmsg.extd = ${frame.extended ? 1 : 0};\nmsg.data_length_code = ${bytes.length};\nconst uint8_t data[] = {${arr.join(', ')}};\nmemcpy(msg.data, data, sizeof(data));\ntwai_transmit(&msg, pdMS_TO_TICKS(10));${period ? `  // repeat every ${period} ms` : ''}` });
  } else if (frame.type === 'van') {
    const access = frame.van && frame.van.access || 'write';
    out.push({ title: 'VAN', lang: 'text', code: `VAN frame: IDEN 0x${hex(frame.id, 3)}, ${bytes.length} data bytes: ${bytesToHex(bytes)}\nCOM field: EXT=1 RAK=${frame.van && frame.van.ack ? 1 : 0} R/W=${access === 'read' ? 1 : 0} RTR=${frame.van && frame.van.rtr ? 1 : 0}\nVAN is not CAN: you need a VAN controller (TSS463/TSS461) or a software VAN implementation,\neg. ESP32 + SN65HVD230 transceiver with morcibacsi's esp32_rmt_van_rx (receive) / esp32_arduino_van_writer (transmit).` });
    out.push({ title: 'Arduino (morcibacsi VAN writer, pseudo code)', lang: 'c', code: `uint8_t data[] = {${arr.join(', ')}};\n// van_writer.send_frame(0x${hex(frame.id, 3)}, data, ${bytes.length}, /*require_ack=*/${frame.van && frame.van.ack ? 'true' : 'false'});` });
  } else if (frame.type === 'lin') {
    const pid = linPid(frame.id);
    const enhanced = !(frame.lin && frame.lin.checksum === 'classic');
    const cs = linChecksum(bytes, enhanced ? pid : null);
    out.push({ title: 'LIN', lang: 'text', code: `LIN frame id 0x${hex(frame.id, 2)} -> protected id (PID) 0x${hexByte(pid)}\nOn the wire: BREAK SYNC(0x55) PID(0x${hexByte(pid)}) | ${bytesToHex(bytes)} | checksum 0x${hexByte(cs)} (${enhanced ? 'enhanced, LIN 2.x' : 'classic, LIN 1.x'})\nThe master sends the header; the slave that publishes this frame sends data + checksum.` });
    out.push({ title: 'Arduino LIN (raw UART, pseudo code)', lang: 'c', code: `// break: hold TX low >= 13 bits (eg. Serial.begin(9600); write(0x00); then back to 19200)\nuint8_t frame[] = {0x55, 0x${hexByte(pid)}, ${arr.join(', ')}, 0x${hexByte(cs)}};\nSerial1.write(frame, sizeof(frame));` });
  }
  return out;
}
